# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's code
COPY . .

# Make port 8080 available
EXPOSE 8080

# Run the app when the container launches
CMD ["npm", "run", "serve"]
